version: "3.8"

volumes:
  db_volume:
    driver: local

networks:
  php_advanced_course:
    driver: bridge

services:
  app:
#    image: "php:8.1-apache"
    build:
      context: .docker/php
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    networks:
      - php_advanced_course

  adminer:
    image: "adminer:4.8.0"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - php_advanced_course

  db:
    image: "mysql:8.0"
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret-password
    volumes:
      - "db_volume:/var/lib/mysql"
    networks:
      - php_advanced_course